services:
  
  # ====================================================================================================================
  # H2 SERVER
  # ====================================================================================================================
#  h2-docker:
#    image: oscarfonts/h2:latest
#    container_name: dev-h2
#    ports:
#      - "1521:1521"  # TCP port
#      - "8181:81"    # Web Console port
#    environment:
#      H2_OPTIONS: "-ifNotExists"
#    volumes:
#      - ./h2-data:/opt/h2-data
#    networks:
#      - dev-network

  
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  pg-docker: #Nome do serviço ==Host name/address
    image: postgres:latest
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: 1234567
#      POSTGRES_USER: rafaelgrando
    ports:
      - 5433:5432
    volumes:
      - E:\Devsuperior\postgresql:/var/lib/postgresql/data
    networks:
      - dev-network
  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - 5050:80
    volumes:
      - E:\Devsuperior\pgadmin:/var/lib/pgadmin
    depends_on:
      - pg-docker
    networks:
      - dev-network
# ======================================================================================================================
# REDE
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge